[project]
name = "ticket-contracts"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.nft-contract]
path = "contracts/nft-contract.clar"

[contracts.ticket-nft]
path = "contracts/ticket-nft.clar"
depends_on = ["nft-contract"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
